Sprint 2/step 2
ValeriiaKuz/BurgerProject pull request #4
Opened 2023-04-19 08:13 UTC by ValeriiaKuz

some problems with reducers, but all work

2023-04-19 09:14 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/UHLZTMM3CwiapA>;

- В компоненте app-header требуется поправить семантику, иконки тоже должны быть обёрнуты в ссылку.

  ```js
  <a href='#' class='......'>
    <BurgerIcon type='primary' /> Конструктор
  </a>
  ```

  А также, текст тоже должен быть активного цвета: <https://disk.yandex.com/i/5xDM0_c9L36KSQ>;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты <https://disk.yandex.com/i/47Iuczvc_g1ODg>;

- Если значения нет, то нужно использовать null, а не пустой объект.

### **Сделает код лучше:**

- Лучше делать проект в корне github репозитория, а не в отдельной папке;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/app/app.jsx
> +  };
**Надо исправить:**

Нужно вынести экшн в отдельный файлик, в идеале, положить в `actions/get-ingredients.js`

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/app/app.jsx
> +        })
**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

Т.к. проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +  });
**Надо исправить:**

здесь и далее. 

У вас как-то сложно сделан механизм разделения)) 

Лучше изначально разделить булку и ингредиенты, и потом делать рендер в `jsx`, а не сразу через map:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: addedIngredients.find(item => item.type === 'bun'),
    ingredients: addedIngredients.filter(item => item.type !== 'bun'),
  };
}, [addedIngredients]);
```

булки у нас в любом случае будут одни и те же, поэтому не нужно их как-то разделять.

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/burger-constructor/burger-constructor.js
> +  }, [addedIngredients]);
**Можно лучше:**

Лучше это делать через `redux`, чтобы поддерживать актуальное состояние конструктора))

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/burger-ingredients/burger-ingredients.js
> +  );
**Можно лучше:** 

В данном случае лучше всё в 1 `useMemo` объеденить. 

```js
const {sauces, mains, buns} = useMemo(...);
```

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/components/burger-ingredients/burger-ingredients.js
> +  }, []);
**Можно лучше:**

Для работы с DOM лучше использовать ref's `useRef()`

2023-04-19 09:14 UTC, ArslanDev666 commented on react-burger/src/components/main-components-wrapper/component-wrapper.js
> +  };
**Надо исправить:**

аналогичное замечание есть в компоненте `app`.

единственное что, формировать заказ нужно вне экшена. т.е. 

```js
const handleOrderClick = () => {
 // Формирование массива из id ингредиентов
 const ingredientsIds = [...];
 
 dispatch(getOrderNumber(ingredientsIds))

 // какие-то ещё действия
}

<Button
  onClick={handleOrderClick}
  htmlType="button"
  type="primary"
  size="medium"
>
  Оформить заказ
</Button>
```

2023-04-19 09:14 UTC, ArslanMustafin commented on react-burger/src/services/reducers/add-ingredient.js
> +          : action.payload.ingredient.price;
Попробую это упростить, если будет время)) при следующей проверке отпишу. А так пробуйте сами, как минимум нужно избавиться от трудно читаемого кода (тернарки), лучше писать обычные if-ы, и постарайтесь не делать `else if`)

2023-04-19 09:14 UTC, ArslanDev666 commented on react-burger/src/services/reducers/add-ingredient.js
> +        addedIngredients: [...state.addedIngredients].filter(
**Можно лучше:**

тут нет необходимости копировать массив, т.к filter возвращает новый массив, он не мутирует исходный)

2023-04-19 09:14 UTC, ArslanDev666 commented on react-burger/src/services/reducers/opened-ingredient.js
> +  openedIngredient: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-19 09:14 UTC, ArslanDev666 commented on react-burger/src/services/reducers/opened-ingredient.js
> +        openedIngredient: {},
И вот тут тоже не забудьте

2023-04-20 08:54 UTC, ValeriiaKuz commented
Не понимаю, как можно на данным этапе это поменять:"Лучше делать проект в корне github репозитория, а не в отдельной папке;". Git - вообще очень сложно мне дается. Нет никакого опыта ни в чем. :)

2023-04-21 06:35 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-21 06:35 UTC, ArslanMustafin commented on react-burger/src/services/reducers/add-ingredient.js
> +// Код не стал короче, но вроде бы стал более читабельный. Танцы с бубном по добавлению булок в начало, а то у меня ломается сортировка. Другого решения не смогла придумать:(
Рассмотрите вариант отделение булки и ингредиентов): 

```js
const initialState = {
  bun: null,
  ingredients: [],
};

export const constructorReducer = (state = initialState, action) => {
  switch (action.type) {
    case CONSTRUCTOR_ADD: {
      if (action.payload.type === "bun") {
        return { ...state, bun: action.payload };
      }
      return {
        ...state,
        ingredients: [...state.ingredients, action.payload],
      };
    }
    case CONSTRUCTOR_DELETE: {
      return {
        ...state,
        ingredients: [
          ...state.ingredients.slice(0, action.payload),
          ...state.ingredients.slice(action.payload + 1),
        ],
      };
    }
    case CONSTRUCTOR_REORDER: {
      const ingredients = [...state.ingredients];
      ingredients.splice(
        action.payload.to,
        0,
        ingredients.splice(action.payload.from, 1)[0]
      );
      return {
        ...state,
        ingredients,
      };
    }
    case CONSTRUCTOR_RESET: {
      return initialState;
    }
    default: {
      return state;
    }
  }
};
```

2023-04-21 06:35 UTC, ArslanMustafin commented on react-burger/src/services/reducers/add-ingredient.js
> +  orderPrice: 0,
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```js
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

2023-04-21 06:43 UTC, ArslanDev666 commented
> Не понимаю, как можно на данным этапе это поменять:"Лучше делать проект в корне github репозитория, а не в отдельной папке;". Git - вообще очень сложно мне дается. Нет никакого опыта ни в чем. :)

При желании можно исправить, но я тоже не вижу смысла исправлять что-то на этом этапе, тем более это была просто рекомендация на будущее)) По гиту советую посмотреть видосики на ютубе, https://www.youtube.com/playlist?list=PL0k-9Y7O1GweYJHN0QfrW2rUjWxrszsg_

2023-04-27 10:17 UTC, merged