sprint-3/step-1
ValeriiaKuz/BurgerProject pull request #5
Opened 2023-05-04 14:35 UTC by ValeriiaKuz

2023-05-04 14:35 UTC, ValeriiaKuz commented
Очень тяжело далось

2023-05-04 15:04 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с формами
- Настроены все редиректы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return `<Navigate to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Navigate`)
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
- Добавление в конструктор осуществляется при нажатии на ингредиент - это некорреткно, необходимо добавлять только через `Dnd` 
- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент 
```
{path="/"}:
setCookie('name', value, { path: '/' }).
```
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-04 15:04 UTC, andryxxa93 commented on react-burger/src/pages/login/login.js
> +  if (user.name && user.email) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-05-06 09:27 UTC, andryxxa93 commented
**Необходимо исправить**
- У вас не срабатывает обновление токена при ошибке. Дело в функции `getResponse`. Рекомендую сделать её такой - так будет работать. 
```
const getResponse = (res) => {
    return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-05-06 09:51 UTC, ValeriiaKuz commented
Спасибо за ваши комментарии. Обратная связь очень помогает

2023-05-07 05:54 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-19 03:41 UTC, merged